package de.unileipzig.irpact.util.R.builder;

import de.unileipzig.irpact.util.R.builder.ggplot2.*;

import java.time.LocalDateTime;

/**
 * @author Daniel Abitz
 */
public final class RScriptFactory {

    public static final StringSettings SETTINGS = new StringSettings();

    private RScriptFactory() {
    }

    private static Comment getDate() {
        return new Comment("date: " + LocalDateTime.now());
    }

    private static Comment getAutoGenerated() {
        return new Comment("automatic generated Rscript");
    }

    private static Comment getUsageComment() {
        return new Comment("usage: Rscript <script name> <input file> <output file>");
    }

    private static RScriptBuilder newBuilder() {
        RScriptBuilder builder = new RScriptBuilder();
        builder.setSettings(SETTINGS);
        return builder;
    }

    //=========================
    //line chart
    //=========================

    public static RScriptBuilder lineChart0(
            String title,
            String xarg, String yarg, String grparg,
            String xlab, String ylab, String grplab,
            String sep,
            String[] colClasses,
            String[] xBreakes,
            int lineWidth,
            int width, int height,
            String encoding) {
        Args args = new Args("args", 2);

        Library lib = new Library("ggplot2");

        ReadDotCsv csv = new ReadDotCsv("inputdata");
        csv.setFileName(args.getNamedIndex(1));
        csv.setHeader(true);
        csv.setSep(sep);
        csv.setColClasses(colClasses);

        Ggplot plot = new Ggplot();

        GeomLine geomLine = new GeomLine();
        geomLine.setData(csv.getReturnName());
        geomLine.setSize(lineWidth);
        geomLine.aes().setX(xarg);
        geomLine.aes().setY(yarg);
        geomLine.aes().setGroup(grparg);
        geomLine.aes().setColour(grparg);

        Labs labs = new Labs();
        labs.setTitle(title, encoding);
        labs.setX(xlab, encoding);
        labs.setY(ylab, encoding);
        labs.setColour(grplab, encoding);

        ScaleXContinuous scaleXContinuous = new ScaleXContinuous();
        scaleXContinuous.setBreaks(xBreakes);

        Theme theme = new Theme();
        theme.setPlotTitleHjust(0.5);

        Ggsave save = new Ggsave();
        save.setFileName(args.getNamedIndex(2));
        save.setWidth(width);
        save.setHeight(height);

        RScriptBuilder builder = newBuilder();

        builder.add(getDate());
        builder.add(getAutoGenerated());
        builder.add(new Comment("type: line chart v0"));
        builder.add(getUsageComment());
        builder.newLine();
        builder.add(args);
        builder.newLine();
        builder.add(lib);
        builder.newLine();
        builder.add(csv);
        builder.addLinked(plot, geomLine, labs, scaleXContinuous, theme);
        builder.add(save);
        builder.devoff();

        return builder;
    }

    //=========================
    //interaction line chart
    //=========================

    public static RScriptBuilder interactionLineChart0(
            String title,
            String xarg, String yarg, String grparg, String distinctarg,
            String xlab, String ylab, String grplab, String distinctlab,
            String distinct0lab, String distinct1lab,
            String sep,
            String[] colClasses,
            String[] xBreakes,
            int lineWidth,
            int width, int height,
            String encoding) {
        Args args = new Args("args", 2);

        Library lib = new Library("ggplot2");

        ReadDotCsv csv = new ReadDotCsv("inputdata");
        csv.setFileName(args.getNamedIndex(1));
        csv.setHeader(true);
        csv.setSep(sep);
        csv.setColClasses(colClasses);

        Ggplot plot = new Ggplot();

        GeomLine geomLine = new GeomLine();
        geomLine.setData(csv.getReturnName());
        geomLine.setSize(lineWidth);
        geomLine.aes().setX(xarg);
        geomLine.aes().setY(yarg);
        geomLine.aes().setGroupInteraction(grparg, distinctarg);
        geomLine.aes().setColour(grparg);
        geomLine.aes().setLinetype(distinctarg);

        Labs labs = new Labs();
        labs.setTitle(title, encoding);
        labs.setX(xlab, encoding);
        labs.setY(ylab, encoding);
        labs.setColour(grplab, encoding);
        labs.setLinetype(distinctlab, encoding);

        ScaleXContinuous scaleXContinuous = new ScaleXContinuous();
        scaleXContinuous.setBreaks(xBreakes);

        ScaleLinetypeManual scaleLinetypes = new ScaleLinetypeManual();
        scaleLinetypes.setTwoNamend(
                distinct0lab,
                "solid",
                distinct1lab,
                "dotted"

        );

        Theme theme = new Theme();
        theme.setPlotTitleHjust(0.5);

        Ggsave save = new Ggsave();
        save.setFileName(args.getNamedIndex(2));
        save.setWidth(width);
        save.setHeight(height);

        RScriptBuilder builder = newBuilder();

        builder.add(getDate());
        builder.add(getAutoGenerated());
        builder.add(new Comment("type: interaction line chart v0"));
        builder.add(getUsageComment());
        builder.newLine();
        builder.add(args);
        builder.newLine();
        builder.add(lib);
        builder.newLine();
        builder.add(csv);
        builder.addLinked(plot, geomLine, scaleLinetypes, labs, scaleXContinuous, theme);
        builder.add(save);
        builder.devoff();

        return builder;
    }

    //=========================
    //stacked bar chart
    //=========================

    public static RScriptBuilder stackedBarChart0(
            String title,
            String xarg, String yarg, String fillarg,
            String xlab, String ylab, String filllab,
            String sep,
            String[] colClasses,
            String[] xBreakes,
            int width, int height,
            String encoding) {

        Args args = new Args("args", 2);

        Library lib = new Library("ggplot2");

        ReadDotCsv csv = new ReadDotCsv("inputdata");
        csv.setFileName(args.getNamedIndex(1));
        csv.setHeader(true);
        csv.setSep(sep);
        csv.setColClasses(colClasses);

        Ggplot plot = new Ggplot();
        plot.setData(csv.getReturnName());
        plot.aes().setX(xarg);
        plot.aes().setY(yarg);
        plot.aes().setFill(fillarg);

        GeomBar geomBar = new GeomBar();
        geomBar.setPosition(Element.STACK);
        geomBar.setStat(Element.IDENTITY);

        Labs labs = new Labs();
        labs.setTitle(title, encoding);
        labs.setX(xlab, encoding);
        labs.setY(ylab, encoding);
        labs.setFill(filllab, encoding);


        ScaleXContinuous scaleXContinuous = new ScaleXContinuous();
        scaleXContinuous.setBreaks(xBreakes);

        Theme theme = new Theme();
        theme.setPlotTitleHjust(0.5);

        Ggsave save = new Ggsave();
        save.setFileName(args.getNamedIndex(2));
        save.setWidth(width);
        save.setHeight(height);

        RScriptBuilder builder = newBuilder();

        builder.add(getDate());
        builder.add(getAutoGenerated());
        builder.add(new Comment("type: stacked bar chart v0"));
        builder.add(getUsageComment());
        builder.newLine();
        builder.add(args);
        builder.newLine();
        builder.add(lib);
        builder.newLine();
        builder.add(csv);
        builder.addLinked(plot, geomBar, labs, scaleXContinuous, theme);
        builder.add(save);
        builder.devoff();

        return builder;
    }
}
